apiVersion: v1
kind: ConfigMap
metadata:
  name: service-order-config
  namespace: fiap-oficina
  labels:
    app: service-order-service
data:
  DB_HOST: "mysql-service-order"
  DB_PORT: "3306"
  DB_NAME: "oficina_db"
  DB_USERNAME: "oficina_user"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"
  APP_BASE_URL: "https://api.oficina.com"
  RESEND_FROM_EMAIL: "oficina@fabrincahub.com"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  LOGGING_LEVEL_COM_FIAP: "INFO"
