apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: fiap-oficina
type: Opaque
stringData:
  DB_PASSWORD: "oficina_pass"
  MYSQL_ROOT_PASSWORD: "root_password"
  MYSQL_SO_PASSWORD: "oficina_pass"
