apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: fiap-oficina
  labels:
    app: tech-challenge-fase2
type: Opaque
data:
  DB_PASSWORD: b2ZpY2luYV9wYXNz
  MYSQL_ROOT_PASSWORD: b2ZpY2luYV9wYXNz
  RESEND_API_KEY: cmVfWUxIaWlWUWhfTm5qV2JnTnBIQm1hOXNqQ1UzNXJzdk54